"""ADOPT-090 to ADOPT-094 — how a repository finds out that ai-sdlc governs it.

A directory nothing points at is a directory nobody reads. Two surfaces, and
they are not alternatives: the import in `CLAUDE.md` is always-on and cannot be
missed, and the skill is loaded on demand and can afford detail.
"""

import unittest

from _adopt import repository, NEWER_PIN, PIN
import _adopt  # noqa: F401
from adopt import ADOPTION_PAGE, SKILL_FILE, apply, verify

CONFIG = "capabilities:\n  - hygiene\n"
PIPELINE = (
    "capabilities:\n  - hygiene\n  - consistency\n  - labels\n  - release\n"
    "  - pipeline\nowners:\n  - someone\ndashboard_issue: 7\n"
    "profiles:\n  - mkdocs\nskills:\n  - ci-watch\n"
)


def adopted(config=CONFIG, pin=PIN):
    root = repository({".ai-sdlc/repo-config.yml": config})
    apply(root, pin=pin)
    return root


class TestTheGeneratedPage(unittest.TestCase):
    def test_every_adoption_gets_one(self):  # ADOPT-090
        self.assertTrue((adopted() / ADOPTION_PAGE).is_file())

    def test_it_names_the_installed_version(self):  # ADOPT-090
        self.assertIn(PIN[0], (adopted() / ADOPTION_PAGE).read_text())

    def test_it_lists_the_capabilities_in_force(self):  # ADOPT-090
        text = (adopted(PIPELINE) / ADOPTION_PAGE).read_text()
        for capability in ("substrate", "hygiene", "labels", "release", "pipeline"):
            self.assertIn(f"`{capability}`", text)

    def test_it_lists_the_callers_actually_installed(self):  # ADOPT-090
        text = (adopted(PIPELINE) / ADOPTION_PAGE).read_text()
        self.assertIn(".github/workflows/dashboard.yml", text)

    def test_it_omits_a_caller_this_repository_does_not_install(self):  # ADOPT-090
        self.assertNotIn("dashboard.yml", (adopted() / ADOPTION_PAGE).read_text())

    def test_it_lists_the_pipeline_labels_this_repository_uses(self):  # ADOPT-090
        """The evidence for this shape: a consumer hand-maintained a label table
        that disagreed with the manifest in four colours, and 27 references to a
        state that no longer existed. Both were copies of generated things."""
        text = (adopted(PIPELINE) / ADOPTION_PAGE).read_text()
        self.assertIn("ai-triage-queued", text)

    def test_a_renamed_label_follows_the_configuration(self):  # ADOPT-090
        text = (adopted(PIPELINE + "labels:\n  parked: on-ice\n") / ADOPTION_PAGE).read_text()
        self.assertIn("on-ice", text)

    def test_no_pipeline_means_no_state_table(self):  # ADOPT-090
        self.assertNotIn("ai-triage-queued", (adopted() / ADOPTION_PAGE).read_text())

    def test_it_lists_the_skills_installed_here(self):  # ADOPT-090
        self.assertIn("`ci-watch`", (adopted(PIPELINE) / ADOPTION_PAGE).read_text())


class TestThePageIsManaged(unittest.TestCase):
    def test_it_carries_the_provenance_header(self):  # ADOPT-091
        self.assertIn("ai-sdlc:", (adopted() / ADOPTION_PAGE).read_text())

    def test_verify_catches_an_edit_to_it(self):  # ADOPT-091
        root = adopted()
        (root / ADOPTION_PAGE).write_text("hand written\n")
        self.assertFalse(verify(root, pin=PIN).ok)

    def test_it_is_rewritten_on_upgrade(self):  # ADOPT-091
        root = adopted()
        apply(root, pin=NEWER_PIN)
        self.assertIn(NEWER_PIN[0], (root / ADOPTION_PAGE).read_text())

    def test_a_changed_configuration_changes_it(self):  # ADOPT-091
        root = adopted()
        (root / ".ai-sdlc/repo-config.yml").write_text(CONFIG + "skills:\n  - ci-watch\n")
        apply(root, pin=PIN)
        self.assertIn("`ci-watch`", (root / ADOPTION_PAGE).read_text())


class TestThePageExplainsNothing(unittest.TestCase):
    """ADOPT-092 — it holds resolved state and links; a restatement rots.

    Nothing here says how anything *behaves*. That is what the links are for,
    and they are pinned to the commit this repository actually runs.
    """

    def test_it_links_the_specification_at_the_pinned_commit(self):  # ADOPT-092
        text = (adopted() / ADOPTION_PAGE).read_text()
        self.assertIn(f"https://github.com/derekwinters/ai-sdlc/blob/{PIN[1]}/docs/spec/", text)

    def test_it_links_only_what_applies_here(self):  # ADOPT-092
        text = (adopted() / ADOPTION_PAGE).read_text()
        self.assertNotIn("docs/spec/dashboard.md", text)

    def test_a_pipeline_repository_gets_the_pipeline_pages(self):  # ADOPT-092
        text = (adopted(PIPELINE) / ADOPTION_PAGE).read_text()
        self.assertIn("docs/spec/dashboard.md", text)

    def test_it_says_not_to_edit_it(self):  # ADOPT-092
        self.assertIn("Do not edit this file", (adopted() / ADOPTION_PAGE).read_text())


class TestTheSkill(unittest.TestCase):
    def test_every_adoption_installs_it(self):  # ADOPT-093
        self.assertTrue((adopted() / SKILL_FILE).is_file())

    def test_it_sits_where_claude_code_requires(self):  # ADOPT-093
        self.assertEqual(SKILL_FILE, ".claude/skills/ai-sdlc/SKILL.md")

    def test_the_description_names_what_an_agent_is_about_to_touch(self):  # ADOPT-093
        """The description is the only text a model sees when deciding whether
        to load anything, so it is load-bearing in a way the body is not. It
        needs concrete nouns, not an abstract offer of context."""
        text = (adopted() / SKILL_FILE).read_text().lower()
        head = text.split("---")[1]
        for noun in ("issue", "label", "milestone", "triage", "release", "workflow"):
            self.assertIn(noun, head, noun)

    def test_it_points_at_the_generated_page(self):  # ADOPT-093
        self.assertIn(ADOPTION_PAGE, (adopted() / SKILL_FILE).read_text())

    def test_it_points_at_the_configuration(self):  # ADOPT-093
        self.assertIn(".ai-sdlc/repo-config.yml", (adopted() / SKILL_FILE).read_text())


class TestTheSkillsFrontmatterSurvives(unittest.TestCase):
    """ADOPT-094 — provenance goes *inside* the frontmatter block.

    A `#` comment before a `---` block stops it being frontmatter at all, and a
    skill whose frontmatter does not parse is a skill no agent ever loads. This
    is the one file where the header cannot go on top.
    """

    def test_the_file_opens_with_the_frontmatter_fence(self):  # ADOPT-094
        self.assertTrue((adopted() / SKILL_FILE).read_text().startswith("---\n"))

    def test_the_name_is_still_in_the_frontmatter(self):  # ADOPT-094
        head = (adopted() / SKILL_FILE).read_text().split("---")[1]
        self.assertIn("name: ai-sdlc", head)

    def test_the_provenance_is_inside_the_block(self):  # ADOPT-094
        head = (adopted() / SKILL_FILE).read_text().split("---")[1]
        self.assertIn("ai-sdlc: derekwinters/ai-sdlc@", head)

    def test_it_still_classifies_as_managed(self):  # ADOPT-094
        self.assertTrue(verify(adopted(), pin=PIN).ok)

    def test_verify_catches_an_edit_to_it(self):  # ADOPT-094
        root = adopted()
        text = (root / SKILL_FILE).read_text()
        (root / SKILL_FILE).write_text(text + "\nand a local paragraph\n")
        self.assertFalse(verify(root, pin=PIN).ok)

    def test_a_second_apply_leaves_it_alone(self):  # ADOPT-094
        root = adopted()
        self.assertNotIn(SKILL_FILE, apply(root, pin=PIN).written)


if __name__ == "__main__":
    unittest.main()
